# Project information
site_name: Agentic AI Workshop
site_description: Agentic AI Workshop by ADP Brazil Labs
site_url: https://dougtrajano.github.io/agentic-ai-workshop/
site_author: ADP Brazil Labs

# Repository
repo_name: agentic-ai-workshop
repo_url: https://github.com/DougTrajano/agentic-ai-workshop

# Other
use_directory_urls: false
copyright: Copyright 2025 ADP Brazil Labs. Licensed under the Apache License, Version 2.0.

theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)" # get system preference
      scheme: default
      primary: red
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # get system preference
      scheme: slate
      primary: red
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

nav:
  - Visão Geral:
    - Introdução: index.md
    - Pré-requisitos: prerequisites.md
    - Instrutores:
      - Douglas Trajano: instructors/douglas-trajano.md
    - Oferecimento: adp-brazil-labs.md
  - Agentic AI:
    - Introdução: agentic-ai/index.md
    - Generative AI: agentic-ai/generative-ai.md
    - AI Agents vs. AI Workflows: agentic-ai/agents-vs-workflows.md
    - Context Engineering:
      - Introdução: agentic-ai/context-engineering/index.md
      - Prompt Engineering:
        - Introdução: agentic-ai/context-engineering/prompt-engineering/index.md
        - Zero/Few-Shot: agentic-ai/context-engineering/prompt-engineering/zero-shot-few-shot.md
        - Chain of Thought: agentic-ai/context-engineering/prompt-engineering/chain-of-thought.md
        - Meta Prompting: agentic-ai/context-engineering/prompt-engineering/meta-prompting.md
        - Role-Based Prompts: agentic-ai/context-engineering/prompt-engineering/role-based-prompts.md
        - Agent Prompting: agentic-ai/context-engineering/prompt-engineering/agent-prompting.md
        - Advanced Techniques: agentic-ai/context-engineering/prompt-engineering/advanced-techniques.md
        - Best Practices: agentic-ai/context-engineering/prompt-engineering/best-practices.md
      - Long-Horizon Tasks: agentic-ai/context-engineering/long-horizon-tasks.md
      - Writing Tools: agentic-ai/context-engineering/writing-tools.md
    - AI Agents:
      - AI Agents: agentic-ai/agents/index.md
      - Memory Management: agentic-ai/agents/memory.md
      - State Management: agentic-ai/agents/state.md
      - Knowledge Base: agentic-ai/agents/knowledge-base.md
      - Tools & MCP: agentic-ai/agents/tools.md
    - AI Frameworks:
      - AI Frameworks: agentic-ai/frameworks/index.md
      - LangGraph: agentic-ai/frameworks/langgraph.md
      - Pydantic AI: agentic-ai/frameworks/pydantic-ai.md
      - Strands Agents: agentic-ai/frameworks/strands-agents.md
      - smolagents: agentic-ai/frameworks/smolagents.md
    - AI Observability: agentic-ai/ai-observability.md
  - Hands-on Workshop:
    - Hands-on Workshop: workshop/index.md
    - Setup do Ambiente: workshop/setup.md
    - HR Synthetic Database: workshop/database.md
    - People Analytics Agent: workshop/people-analytics-agent.md
    - Próximos Passos: workshop/next-steps.md
  - Recursos Adicionais: resources.md

plugins:
  - tooltips
  - search
  - section-index
  - git-revision-date-localized
  - glightbox
  - exclude:
      glob:
        - diagrams/*

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/adpbrazillabs/
      name: ADP Brazil Labs - LinkedIn
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/adpbrazillabs
      name: ADP Brazil Labs - X
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/adpbrazillabs/
      name: ADP Brazil Labs - Instagram
    - icon: fontawesome/brands/medium
      link: https://medium.com/adp-brazil-labs
      name: ADP Brazil Labs - Medium

extra_css:
  # - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
  - stylesheets/extra.css
  - stylesheets/tooltip.css

extra_javascript:
  # - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.js
  - javascripts/tables.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
