resources:
  jobs:
    setup_app_database:
      name: ${var.base_name}-setup-app-db
      description: "Setup Lakebase PostgreSQL database and tables for development"
      tasks:
        - task_key: setup_app_database
          notebook_task:
            notebook_path: ../src/jobs/setup_app_lakebase.py
      parameters:
        - name: instance_name
          default: ${resources.database_instances.app-database.name}
        - name: database
          default: ${var.database_name}
        - name: app_name
          default: ${var.base_name}-chat-app
        - name: port
          default: "5432"

  database_instances:
    app-database:
      name: ${var.base_name}-lakebase
      capacity: CU_1

  database_catalogs:
    agentic-ai-workshop:
      database_instance_name: ${resources.database_instances.app-database.name}
      name: ${var.base_name}-catalog
      database_name: ${var.database_name}
      create_database_if_not_exists: true

  apps:
    chat-app:
      name: ${var.base_name}-chat-app
      description: AI-powered People Analytics Agent
      resources:
        - name: LAKEBASE
          database:
            database_name: ${resources.database_catalogs.agentic-ai-workshop.database_name}
            instance_name: ${resources.database_catalogs.agentic-ai-workshop.database_instance_name}
            permission: CAN_CONNECT_AND_CREATE
        - name: OPENAI_API_KEY
          secret:
            key: API_KEY
            permission: READ
            scope: openai-credentials

      source_code_path: ../src/app
      permissions:
        - level: CAN_USE
          user_name: ${var.user_name}
